Rozhan Moosavi

In [4]:
import numpy as np

making an array

In [5]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [18]:
b = np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
c = np.arange(10, 20, 2)
c

array([10, 12, 14, 16, 18])

making a random array

In [17]:
d = np.random.randint(0, 20, (3,3))
d

array([[ 4, 13, 18],
       [ 1,  4, 14],
       [10,  9, 14]])

shape & size

In [19]:
print('shape of array :' , b.shape)
print('size of array :' , np.size(b))
print('length of array :' , len(b))

shape of array : (12,)
size of array : 12
length of array : 12


reshaping an array

In [21]:
b_reshaped = b.reshape(3,4)
b_reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
print('shape of the reshaped array :' , b_reshaped.shape)
print('size of the reshaped array :' , np.size(b_reshaped))
print('length of the reshaped array :' , len(b_reshaped))

shape of the reshaped array : (3, 4)
size of the reshaped array : 12
length of the reshaped array : 3


martix

In [26]:
from sympy import *
Matrix(b_reshaped)

Matrix([
[0, 1,  2,  3],
[4, 5,  6,  7],
[8, 9, 10, 11]])

In [27]:
matrix = b.reshape(2,2,3)
matrix

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [30]:
Matrix([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Matrix([
[[0, 1, 2],   [3, 4, 5]],
[[6, 7, 8], [9, 10, 11]]])

In [33]:
Matrix([matrix])

Matrix([[[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]])